import type { AppTheme, KeyboardTheme } from "@/types"

export const appThemes: AppTheme[] = [
  {
    id: "keeby-light",
    name: "Keeby Light",
    background: "#f4f4f6",
    foreground: "#111111",
    muted: "#8a8a8f",
    accent: "#ff7a45",
    fontClass: "",
  },
  {
    id: "pure-white",
    name: "Pure White",
    background: "#ffffff",
    foreground: "#171717",
    muted: "#a1a1aa",
    accent: "#2563eb",
    fontClass: "",
  },
  {
    id: "dark",
    name: "Dark",
    background: "#0a0a0a",
    foreground: "#ededed",
    muted: "#52525b",
    accent: "#3b82f6",
    fontClass: "",
  },
  {
    id: "oled",
    name: "OLED",
    background: "#000000",
    foreground: "#ffffff",
    muted: "#27272a",
    accent: "#6366f1",
    fontClass: "",
  },
  {
    id: "coffee",
    name: "Coffee Shop",
    background: "#1c1917",
    foreground: "#f5f5f4",
    muted: "#44403c",
    accent: "#d97706",
    fontClass: "",
  },
  {
    id: "rain",
    name: "Rain",
    background: "#0f172a",
    foreground: "#f8fafc",
    muted: "#334155",
    accent: "#38bdf8",
    fontClass: "",
  },
  {
    id: "night-studio",
    name: "Night Studio",
    background: "#09090b",
    foreground: "#fafafa",
    muted: "#27272a",
    accent: "#a855f7",
    fontClass: "",
  },
]

export const keyboardThemes: KeyboardTheme[] = [
  {
    id: "keeby-retro",
    name: "Keeby Retro",
    keycap: "#ffffff",
    keycapActive: "#fff5f0",
    keycapPressed: "#ffe8dc",
    case: "#1a1a1a",
    plate: "#2d2d2d",
    label: "#1f1f1f",
    labelActive: "#ff7a45",
    lightColor: "#ffffff",
    lightIntensity: 0.8,
    ambientColor: "#f4f4f6",
    modifierBg: "#737373",
    modifierLabel: "#ffffff",
    numberBg: "#dcdcdc",
    numberLabel: "#1f1f1f",
    escBg: "#ff7a45",
    escLabel: "#ffffff",
  },
  {
    id: "mac-white",
    name: "Mac White",
    keycap: "#e5e7eb",
    keycapActive: "#ffffff",
    keycapPressed: "#d1d5db",
    case: "#d4d4d8",
    plate: "#a1a1aa",
    label: "#52525b",
    labelActive: "#18181b",
    lightColor: "#ffffff",
    lightIntensity: 0.6,
    ambientColor: "#f0f0f0",
  },
  {
    id: "mac-black",
    name: "Mac Black",
    keycap: "#27272a",
    keycapActive: "#3f3f46",
    keycapPressed: "#18181b",
    case: "#09090b",
    plate: "#27272a",
    label: "#a1a1aa",
    labelActive: "#fafafa",
    lightColor: "#ffffff",
    lightIntensity: 0.3,
    ambientColor: "#18181b",
  },
  {
    id: "retro-beige",
    name: "Retro Beige",
    keycap: "#e2dac5",
    keycapActive: "#f0ebd0",
    keycapPressed: "#d4c9a8",
    case: "#c4b99e",
    plate: "#b8a98a",
    label: "#383838",
    labelActive: "#1f1f1f",
    lightColor: "#ffe0b2",
    lightIntensity: 0.5,
    ambientColor: "#e8dccc",
  },
  {
    id: "cyberpunk",
    name: "Cyberpunk",
    keycap: "#1a1a2e",
    keycapActive: "#16213e",
    keycapPressed: "#0f3460",
    case: "#0a0a1a",
    plate: "#1a1a3e",
    label: "#e94560",
    labelActive: "#ff6b6b",
    lightColor: "#e94560",
    lightIntensity: 0.8,
    ambientColor: "#1a1a3e",
  },
  {
    id: "minimal-white",
    name: "Minimal White",
    keycap: "#fafafa",
    keycapActive: "#ffffff",
    keycapPressed: "#f0f0f0",
    case: "#e5e5e5",
    plate: "#d4d4d4",
    label: "#525252",
    labelActive: "#171717",
    lightColor: "#ffffff",
    lightIntensity: 0.6,
    ambientColor: "#fafafa",
  },
  {
    id: "catppuccin",
    name: "Catppuccin",
    keycap: "#313244",
    keycapActive: "#45475a",
    keycapPressed: "#1e1e2e",
    case: "#181825",
    plate: "#313244",
    label: "#a6adc8",
    labelActive: "#cdd6f4",
    lightColor: "#89b4fa",
    lightIntensity: 0.5,
    ambientColor: "#1e1e2e",
  },
  {
    id: "tokyo-night",
    name: "Tokyo Night",
    keycap: "#1a1b26",
    keycapActive: "#24283b",
    keycapPressed: "#0f0f1a",
    case: "#0a0a14",
    plate: "#1a1b26",
    label: "#7aa2f7",
    labelActive: "#a9b1d6",
    lightColor: "#7dcfff",
    lightIntensity: 0.6,
    ambientColor: "#1a1b26",
  },
  {
    id: "nord",
    name: "Nord",
    keycap: "#3b4252",
    keycapActive: "#434c5e",
    keycapPressed: "#2e3440",
    case: "#2e3440",
    plate: "#3b4252",
    label: "#d8dee9",
    labelActive: "#eceff4",
    lightColor: "#88c0d0",
    lightIntensity: 0.5,
    ambientColor: "#3b4252",
  },
  {
    id: "oled-black",
    name: "OLED Black",
    keycap: "#0a0a0a",
    keycapActive: "#1a1a1a",
    keycapPressed: "#000000",
    case: "#000000",
    plate: "#0a0a0a",
    label: "#ffffff",
    labelActive: "#ffffff",
    lightColor: "#ffffff",
    lightIntensity: 0.2,
    ambientColor: "#000000",
  },
  {
    id: "dracula",
    name: "Dracula",
    keycap: "#282a36",
    keycapActive: "#44475a",
    keycapPressed: "#1e1f29",
    case: "#191a21",
    plate: "#282a36",
    label: "#f8f8f2",
    labelActive: "#ffffff",
    lightColor: "#bd93f9",
    lightIntensity: 0.6,
    ambientColor: "#282a36",
  },
  {
    id: "nothing",
    name: "Nothing Style",
    keycap: "#e8e8e8",
    keycapActive: "#f5f5f5",
    keycapPressed: "#d0d0d0",
    case: "#c0c0c0",
    plate: "#b0b0b0",
    label: "#1a1a1a",
    labelActive: "#000000",
    lightColor: "#ffffff",
    lightIntensity: 0.5,
    ambientColor: "#f0f0f0",
  },
  {
    id: "transparent",
    name: "Transparent Acrylic",
    keycap: "#ffffff",
    keycapActive: "#f8f8ff",
    keycapPressed: "#e8e8f0",
    case: "#e0e0e8",
    plate: "#d0d0d8",
    label: "#52525b",
    labelActive: "#18181b",
    lightColor: "#a5b4fc",
    lightIntensity: 0.7,
    ambientColor: "#f0f0ff",
  },
]
